apiVersion: v1
kind: Pod
metadata:
  name: downward-api
  namespace: default
spec:
  containers:
  - name: downward-api-container
    image: jihyunbae/downward-api:latest
    ports:
    - containerPort: 8080
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
